name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #一些图标
  cupertino_icons: ^0.1.2
  #轮播
  flutter_swiper: ^1.1.6
  #瀑布流
  flutter_staggered_grid_view: ^0.3.0
  #路由
  # 下面两个是搭配用 不然命令报错
  annotation_route: any
  build_runner: ^1.6.7
  #视频播放
  video_player: ^0.10.2
  #音频播放
  audioplayers: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
